// ============================================================================
// types.ts
// ============================================================================

export type CardType = 'creature' | 'instant' | 'sorcery' | 'land' | 'artifact' | 'enchantment';

export type ManaColor = 'W' | 'U' | 'B' | 'R' | 'G' | 'C';
export type ManaPool = Record<ManaColor, number>;

export interface CardAbility {
  id: string;
  label: string;
  cost: {
    tap?: boolean;
    sacrificeSelf?: boolean;
    discardCards?: number;
    manaLabel?: string;
  };
  effectText: string;
}

/**
 * Machine-readable card effects, layered on top of the free-text `text`
 * field (which stays the source of truth for display). Only mechanically
 * unambiguous, no-choice effects belong here - see engine/effects.ts. Grows
 * as more patterns get automated; anything not covered here still just
 * displays as text and is applied manually by the players.
 */
export interface CreateTokenEffect {
  type: 'createToken';
  /** id of a CardDefinition in TOKEN_POOL (data/cards.ts). */
  tokenId: string;
  /** Defaults to 1. */
  count?: number | 'perCreatureYouControl';
  tapped?: boolean;
  /** Job select style: attach the permanent generating this effect to the
   * (single) token it just created. Only meaningful when count resolves to 1. */
  attachSelfToToken?: boolean;
}

/**
 * Requires the controller to pick a target once the source resolves - see
 * GameState.pendingTarget and engine/actions.ts: chooseTarget. Only
 * generated by onEnter for now.
 */
export interface TapAndStunEffect {
  type: 'tapAndStun';
  targetController: 'opponent';
  targetType: 'artifact' | 'creature' | 'artifactOrCreature';
}

export type CardEffect = CreateTokenEffect | TapAndStunEffect;

/**
 * "[Basic land type]cycling N" and plain "Cycling N" - discard this card
 * from hand, pay N, and either search for a copy of that basic land type
 * (put into hand, then shuffle) or, with no land type, just draw a card.
 */
export interface CyclingAbility {
  cost: string;
  searchLandName?: 'Plains' | 'Island' | 'Swamp' | 'Mountain' | 'Forest';
}

/**
 * A static, continuously-checked buff ("As long as you control N or more
 * lands, this creature gets +X/+Y") - unlike onEnter/onCast, this isn't a
 * one-time trigger; it's re-evaluated live wherever power/toughness matters
 * (engine/combat.ts, and the client's own combat preview), so it turns on
 * and off automatically as the land count crosses the threshold.
 */
export interface LandCountBuff {
  minLands: number;
  power: number;
  toughness: number;
}

export interface CardDefinition {
  id: string;
  name: string;
  type: CardType;
  subtype?: string;
  costLabel: string;
  power?: number;
  toughness?: number;
  text: string;
  imagePath: string;
  transformsInto?: string;
  producesMana?: ManaColor | 'any' | ManaColor[];
  abilities?: CardAbility[];
  /** Marks this as an Aura or Equipment - what kind of permanent it can be
   * attached to. See CardInstance.attachedToInstanceId and
   * engine/actions.ts: attachCard/detachCard. */
  attachesTo?: 'creature' | 'artifact' | 'land' | 'enchantment' | 'permanent';
  /** Equipment only - mana cost to attach/reattach. Auras don't have this;
   * they attach for free once, right after casting, via the same Attach flow. */
  equipCost?: string;
  /** Fires once, automatically, when this permanent enters the battlefield. */
  onEnter?: CardEffect[];
  /** Fires once, automatically, when this instant/sorcery resolves (right
   * before it goes to the graveyard). */
  onCast?: CardEffect[];
  /** "Cycling" family - activated from hand, see engine/actions.ts: cycleCard. */
  cycling?: CyclingAbility;
  /** See LandCountBuff - a static, always-on-condition-met power/toughness buff. */
  landCountBuff?: LandCountBuff;
}

export interface Counter {
  label: string;
  amount: number;
}

export interface CardInstance {
  instanceId: string;
  defId: string;
  ownerId: string;
  tapped: boolean;
  counters: Counter[];
  damageMarked: number;
  summoningSick: boolean;
  /** If set, this card (an Aura or Equipment) is attached to the battlefield
   * permanent with this instanceId. Cleared automatically if either card
   * leaves the battlefield - see engine/actions.ts and engine/combat.ts. */
  attachedToInstanceId?: string;
  /** Set while tapped, if tapping this card added mana to its owner's pool -
   * records which color, so untapping (before it's spent) correctly gives it
   * back instead of leaving phantom mana in the pool. See engine/actions.ts: toggleTap. */
  producedManaColor?: ManaColor;
}

export type ZoneName = 'library' | 'hand' | 'battlefield' | 'graveyard' | 'exile' | 'commander';

export interface PlayerState {
  id: string;
  name: string;
  life: number;
  zones: Record<ZoneName, CardInstance[]>;
  ready: boolean;
  manaPool: ManaPool;
  hasPlayedLandThisTurn: boolean;
  /** Which CardDefinition id is this player's actual commander, if known.
   * Set at game creation for VS AI (from the chosen deck). Networked
   * Versus play doesn't have deck selection wired up yet, so this stays
   * undefined there for now - see CardActionsPanel for where this gates
   * the "move to commander zone" option. */
  hasDrawnThisTurn: boolean;
  commanderDefId?: string;
  commanderDamageTaken: number;
}

export type Phase =
  | 'pregame'
  | 'untap'
  | 'upkeep'
  | 'draw'
  | 'main1'
  | 'combat_begin'
  | 'declare_attackers'
  | 'declare_blockers'
  | 'combat_damage'
  | 'combat_end'
  | 'main2'
  | 'end'
  | 'cleanup';

export interface CombatAssignment {
  attackerInstanceId: string;
  blockerInstanceIds: string[];
}

/**
 * Mutual Adjustment: a sandbox/correction mode both players must agree to
 * enter (and agree to exit). While active, the usual rules - mana cost,
 * one land per turn, no manual life changes - are all bypassed, so you two
 * can fix a mistake or set up a test scenario together. See
 * engine/actions.ts for exactly which checks this turns off.
 */
export interface MutualAdjustmentState {
  status: 'inactive' | 'requested' | 'active' | 'exit_requested';
  requestedBy?: string;
  agreedBy: string[];
}

export interface GameState {
  players: [PlayerState, PlayerState];
  activePlayerId: string;
  phase: Phase;
  turnNumber: number;
  log: string[];
  winnerId: string | null;
  declaredAttackers: string[];
  combatAssignments: CombatAssignment[];
  mutualAdjustment: MutualAdjustmentState;
  pendingDeaths: string[];
  /** Players who've pressed "Resolve Combat" during the combat_damage step -
   * damage only actually happens once both are in here, so there's always
   * a window to cast an instant in response. See engine/actions.ts. */
  combatReadyPlayers: string[];
  /** Set when an onEnter effect needs its controller to pick a target before
   * it can resolve (e.g. Ice Flan's tap-and-stun) - cleared by CHOOSE_TARGET.
   * Null whenever nothing is waiting on a target. */
  pendingTarget: { sourceInstanceId: string; controllerId: string; effect: TapAndStunEffect } | null;
}

export type GameAction =
  | { type: 'DRAW_CARD' }
  | { type: 'MOVE_CARD'; instanceId: string; toZone: ZoneName }
  | { type: 'SHUFFLE_LIBRARY' }
  | { type: 'TOGGLE_TAP'; instanceId: string; chosenColor?: ManaColor }
  | { type: 'CAST_CARD'; instanceId: string; chosenX?: number }
  | { type: 'ACTIVATE_ABILITY'; instanceId: string; abilityId: string }
  | { type: 'ADJUST_LIFE'; playerId: string; delta: number }
  | { type: 'ADJUST_COUNTER'; instanceId: string; label: string; delta: number }
  | { type: 'FLIP_CARD'; instanceId: string }
  | { type: 'ATTACH_CARD'; instanceId: string; targetInstanceId: string }
  | { type: 'DETACH_CARD'; instanceId: string }
  | { type: 'DECLARE_ATTACKERS'; instanceIds: string[] }
  | { type: 'DECLARE_BLOCKERS'; assignments: CombatAssignment[] }
  | { type: 'ORDER_BLOCKERS'; attackerInstanceId: string; orderedBlockerIds: string[] }
  | { type: 'CHOOSE_TARGET'; targetInstanceId: string }
  | { type: 'CYCLE_CARD'; instanceId: string }
  | { type: 'NEXT_PHASE' }
  | { type: 'END_TURN' }
  | { type: 'READY_TO_START' }
  | { type: 'REQUEST_MUTUAL_ADJUSTMENT' }
  | { type: 'RESPOND_MUTUAL_ADJUSTMENT'; accept: boolean }
  | { type: 'REQUEST_EXIT_MUTUAL_ADJUSTMENT' }
  | { type: 'RESPOND_EXIT_MUTUAL_ADJUSTMENT'; accept: boolean }
  | { type: 'UNDO' }
  | { type: 'CONCEDE' };

export type ActionResult = { ok: true; state: GameState } | { ok: false; error: string };